spring:
  application:
    name: kuruma
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/kuruma
    username: postgres
    password: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# actuator configs for endpoint to get health
# GET /actuator/health
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          show-details: always