server:
  port: 5000
spring:
  application:
    name: kuruma
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/kuruma
    username: postgres
    password: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  main:
    allow-bean-definition-overriding: true
# GET /actuator/health
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          show-details: always

push-notifications:
  public-key: BB_54eE5xN6sw3AsPj4Wz7OlyEeX5qbBoZxgM5lvahdu2VIPIJLzKXq0xBUt4N4LtCQyH72xD6oHkhJ5_7-CLGg
  private-key: Eym-2LdPXdyOGZZWFSVgzHh87-SchTe0qETgRAOhtG8

scheduling:
  push-notification:
#    cron: "1 * * * * *"
    cron: "0 10 * * * *"