version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Tip-Grupo-6/kuruma/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  test:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          .gradlew

workflows:
  my-custom-workflow:
    jobs:
      - test