version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:17-jdk-slim
    steps:
      - checkout  # Checkout your code from the repository
      - run:
          name: Check Java Version
          command: java -version
      - run:
          name: Build and Test
          command: ./gradlew test
