version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:17-jdk-slim
    steps:
      - checkout
      - run:
          name: Check Java Version
          command: java -version
      - run:
          name: Model tests
          command: ./gradlew test --tests "com.tip.kuruma.models.*"
      - run:
            name: Service tests
            command: ./gradlew test --tests "com.tip.kuruma.services.*"
#      - run:
#            name: Controller tests
#            command: ./gradlew test --tests "com.tip.kuruma.controllers.*"
